/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import fachada.Fachada;
import fachada.IFachada;
import fachada.MensajeRecibidoDTO;
import java.util.List;
import javax.swing.JOptionPane;
import model.Profesional;
import solicitudes.ApiClient;

/**
 *
 * @author jl4ma
 */
public class FrmAgregarVacunas extends javax.swing.JFrame {

    ExpedienteBean expediente;
    IFachada fachada;
    Profesional profesionalSesion;
    String nombre;
    String idPaciente;
    private List<MensajeRecibidoDTO> mensajes;
    /**
     * Creates new form FrmAgregarAlergias
     */
    public FrmAgregarVacunas(ExpedienteBean expediente, Profesional pro, List<MensajeRecibidoDTO> mensajes, String nombre, String idPaciente) {
        initComponents();
        this.expediente = expediente;
        this.fachada = new Fachada();
        this.profesionalSesion = pro;
        this.mensajes = mensajes;
        this.nombre = nombre;
        this.idPaciente = idPaciente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVacuna = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Vacunas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre vacuna:");

        txtVacuna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVacunaActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVacunaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txtVacuna.getText().isBlank()) {
            ApiClient api = new ApiClient();
            boolean respuesta = api.agregarContenidoAExpediente(idPaciente, "vacunas", txtVacuna.getText());
            if (respuesta) {
                JOptionPane.showMessageDialog(this,
                        "Vacuna agregada con exito",
                        "Volviendo al expediente...",
                        JOptionPane.INFORMATION_MESSAGE);
                expediente.getVacunas().add(txtVacuna.getText());
                FrmVerExpediente frmVerExpediente = new FrmVerExpediente(expediente, nombre, idPaciente, profesionalSesion, mensajes);
                frmVerExpediente.setLocationRelativeTo(null);
                frmVerExpediente.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this,
                        "Algo salio mal",
                        "Intentelo de nuevo",
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Escriba algo",
                    "Texto en Blanco",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmVerExpediente frmVerExpediente = new FrmVerExpediente(expediente, nombre, idPaciente, profesionalSesion, mensajes);
        frmVerExpediente.setLocationRelativeTo(null);
        frmVerExpediente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtVacuna;
    // End of variables declaration//GEN-END:variables
}
