/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import fachada.Fachada;
import fachada.IFachada;
import fachada.MensajeRecibidoDTO;
import java.util.List;
import javax.swing.JOptionPane;
import model.Profesional;
import solicitudes.ApiClient;

/**
 *
 * @author jl4ma
 */
public class FrmAgregarAlergias extends javax.swing.JFrame {

    ExpedienteBean expediente;
    IFachada fachada;
    Profesional profesionalSesion;
    String nombre;
    String idPaciente;
    private List<MensajeRecibidoDTO> mensajes;

    /**
     * Creates new form FrmAgregarAlergias
     */
    public FrmAgregarAlergias(ExpedienteBean expediente, Profesional pro, List<MensajeRecibidoDTO> mensajes, String nombre, String idPaciente) {
        initComponents();
        this.expediente = expediente;
        this.fachada = new Fachada();
        this.profesionalSesion = pro;
        this.mensajes = mensajes;
        this.nombre = nombre;
        this.idPaciente = idPaciente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAlergia = new javax.swing.JTextField();
        btnAgregarAlergia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Alergias");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Alergia:");

        txtAlergia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAlergia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlergiaKeyTyped(evt);
            }
        });

        btnAgregarAlergia.setText("Agregar");
        btnAgregarAlergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlergiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(48, 48, 48)
                                .addComponent(btnAgregarAlergia))
                            .addComponent(jLabel2)
                            .addComponent(txtAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarAlergia)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29))))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmVerExpediente frmVerExpediente = new FrmVerExpediente(expediente, nombre, idPaciente, profesionalSesion, mensajes);
        frmVerExpediente.setLocationRelativeTo(null);
        frmVerExpediente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarAlergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlergiaActionPerformed
        if (!txtAlergia.getText().isBlank()) {
            ApiClient api = new ApiClient();
            boolean respuesta = api.agregarContenidoAExpediente(idPaciente, "alergias", txtAlergia.getText());
            if (respuesta) {
                JOptionPane.showMessageDialog(this,
                        "Alergia agregada con exito",
                        "Volviendo al expediente...",
                        JOptionPane.INFORMATION_MESSAGE);
                expediente.getAlergias().add(txtAlergia.getText());
                FrmVerExpediente frmVerExpediente = new FrmVerExpediente(expediente, nombre, idPaciente, profesionalSesion, mensajes);
                frmVerExpediente.setLocationRelativeTo(null);
                frmVerExpediente.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this,
                        "Algo salio mal",
                        "Intentelo de nuevo",
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Escriba algo",
                    "Texto en Blanco",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarAlergiaActionPerformed

    private void txtAlergiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlergiaKeyTyped
        char c = evt.getKeyChar();

// Permite solo letras (mayúsculas/minúsculas) y espacios
        if (!Character.isLetter(c) && c != ' ' && c != '\b') {
            evt.consume(); // Ignora la tecla presionada
        }
    }//GEN-LAST:event_txtAlergiaKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlergia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAlergia;
    // End of variables declaration//GEN-END:variables
}
